### ISSUE TITLE
ESlint throws errors about invalid configuration for rule "eol-last"

### ISSUE THREAD

**Issue by mzmiric5** [mxstbr/react-boilerplate#1040]
## Description

The lint script in the project has completely stopped working for me. Originally I thought I might have changed something in my project so I grabbed a fresh clone of the repo, and saw the same issue. I have tested this on 3 physical machines and 2 docker containers with different configurations to determine that the problem is not in global node/npm modules.

Every time I run `npm run lint` I get the following output:

```
> react-boilerplate@3.2.0 lint:eslint /Users/test/workspace/rb
> eslint --ignore-path .gitignore --ignore-pattern internals/scripts "."

/Users/test/workspace/rb/node_modules/eslint-config-airbnb-base/rules/style.js:
	Configuration for rule "eol-last" is invalid:
	Value "always" must be an enum value.

Referenced from: /Users/test/workspace/rb/node_modules/eslint-config-airbnb-base/index.js
Referenced from: airbnb
Referenced from: /Users/test/workspace/rb/package.json
Error: /Users/test/workspace/rb/node_modules/eslint-config-airbnb-base/rules/style.js:
	Configuration for rule "eol-last" is invalid:
	Value "always" must be an enum value.

Referenced from: /Users/test/workspace/rb/node_modules/eslint-config-airbnb-base/index.js
Referenced from: airbnb
Referenced from: /Users/test/workspace/rb/package.json
    at validateRuleOptions (/Users/test/workspace/rb/node_modules/eslint/lib/config/config-validator.js:115:15)
    at /Users/test/workspace/rb/node_modules/eslint/lib/config/config-validator.js:162:13
    at Array.forEach (native)
    at Object.validate (/Users/test/workspace/rb/node_modules/eslint/lib/config/config-validator.js:161:35)
    at load (/Users/test/workspace/rb/node_modules/eslint/lib/config/config-file.js:522:19)
    at /Users/test/workspace/rb/node_modules/eslint/lib/config/config-file.js:391:36
    at Array.reduceRight (native)
    at applyExtends (/Users/test/workspace/rb/node_modules/eslint/lib/config/config-file.js:362:28)
    at load (/Users/test/workspace/rb/node_modules/eslint/lib/config/config-file.js:529:22)
    at /Users/test/workspace/rb/node_modules/eslint/lib/config/config-file.js:391:36
```

What is really interesting is that the lint worked just fine 2 days ago, no updates to the dependencies have been made, and it just started throwing this error yesterday. I have seen at least one more user mention this issue in Gitter.

## Steps to reproduce

1) clone repo
2) `npm run setup`
3) `npm run lint`

# Versions

- Node/NPM: 6.6.0 / 3.10.7
- Browser: n/a

**Comment by peter-mouland** [comment]
this has been fixed with https://github.com/mxstbr/react-boilerplate/pull/1031

**Comment by mzmiric5** [comment]
oh, it's not in master yet, so I've completely missed it. Thanks
