### ISSUE TITLE
extract-intl script can't parse LocaleToggle/messages.js

### ISSUE THREAD

**Issue by Dattaya** [mxstbr/react-boilerplate#1221]
at least on Windows (dev branch):

```bash
> npm run generate language

> react-boilerplate@3.3.0 generate D:\Projects\react-boilerplate
> plop --plopfile internals/generators/index.js "language"

? [LANGUAGE] What is the language you want to add i18n support for (e.g. "fr", "de")? fr

D:\Projects\react-boilerplate\internals\generators\language\index.js:71
            throw err || stderr;
            ^
Error transforming file: app/containers/LocaleToggle/messages.js
SyntaxError: unknown: [React Intl] `defineMessages()` must be called with an object expression with values that are React Intl Message Descriptors, also defined as object expressions.
```

Does anyone else experience this issue?

**Comment by samit4me** [comment]
Confirmed on macOS also, `git checkout dev` > `npm i` > `npm run generate language` > selected the default `fr` > hit enter and then got the same error you reported!

**Comment by Dattaya** [comment]
@justingreenberg, I need your advice. #813 broke `extract-intl` script, here's an error message (it can't parse `app/containers/LocaleToggle/messages`):

```bash
Run extraction on all filesSyntaxError: unknown: [React Intl] `defineMessages()` must be called with an object expression with values that are React Intl Message Descriptors, also defined as object expressions.
  17 | }
  18 |
> 19 | export default defineMessages(
     |                ^
  20 |   getLocaleMessages(appLocales)
  21 | );
  22 |
    at File.buildCodeFrameError (D:\Projects\react-boilerplate\node_modules\babel-core\lib\transformation\file\index.js:431:15)
    at NodePath.buildCodeFrameError (D:\Projects\react-boilerplate\node_modules\babel-traverse\lib\path\index.js:140:26)
    at assertObjectExpression (D:\Projects\react-boilerplate\node_modules\babel-plugin-react-intl\lib\index.js:285:36)
    at PluginPass.CallExpression (D:\Projects\react-boilerplate\node_modules\babel-plugin-react-intl\lib\index.js:316:21)
    at newFn (D:\Projects\react-boilerplate\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (D:\Projects\react-boilerplate\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (D:\Projects\react-boilerplate\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (D:\Projects\react-boilerplate\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (D:\Projects\react-boilerplate\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (D:\Projects\react-boilerplate\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (D:\Projects\react-boilerplate\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (D:\Projects\react-boilerplate\node_modules\babel-traverse\lib\index.js:114:17)
Error transforming file: app/containers/LocaleToggle/messages.js
```

I have only two ideas how to fix it: bring back previous 'dumber' `messages.js`, 
![image](https://cloud.githubusercontent.com/assets/387256/20244535/489afdda-a98f-11e6-9f8d-2e38d3b365a9.png)


or add all the necessary messages like `"boilerplate.containers.LocaleToggle.de"` manually by scanning translations folder and appending these messages to the end (almost) the file.

Do you know better ways to fix this?

**Comment by tlimited** [comment]
I accidentally generated two of the same languages because didn't know it worked the first time and there were no constraints keeping me from doing it. Just a related issue..

**Comment by Dattaya** [comment]
Yep, we should definitely fix that. I've created a new issue: #1234.

**Comment by justingreenberg** [comment]
@Dattaya I'm sorry for the delay in getting to this, I have been swamped at work and personally with weddings and holidays... This is on my list and will investigate asap :)

**Comment by Dattaya** [comment]
@justingreenberg, no problem, it's not a critical bug, so please, take your time.

I went with option # 1 and realized that both of them unfit to solve the issue. By option # 1 I mean this:
 - Revert back #813
 - Add a new action to the language generator that would update LocaleToggle's messages, for example for `fr` it would add:
```js
  fr: {
    id: 'boilerplate.containers.LocaleToggle.fr',
    defaultMessage: 'fr',
  },
```

The problem is that it's specific to the example app, `LocaleToggle` is deleted if you run `npm run clean`. My revived ideas now look like this:
 - Allow to inject actions into the generators (from e.g. internals/generators/plugins folder), sort of an add-on/plugin system and remove everything from that folder during `npm run clean`. This is an action we can inject:
```js
    actions.push({
      type: 'modify',
      path: '../../app/containers/LocaleToggle/messages.js',
      pattern: /(defineMessages\(\{\s*)$/m,
      templateFile: './language/locale-toggle-messages.hbs',
    });
```
 - Alternatively, simplify the example app—do not translate language names and always show them as 'en', 'de', 'fr', …

**Comment by Dattaya** [comment]
Third option is described here: #1251
