### ISSUE TITLE
Itegration of babel-plugin-rewire

### ISSUE THREAD

**Issue by olabalboa** [mxstbr/react-boilerplate#1296]
I have been trying to integrate babel-plugin-rewire to react-boilerplate with inspiration from karma-rewire-istanbul-example made by @jseminck.

The tests runs fine but coverage report generation fails. There are already reported issues regarding rewire and istanbul in both babel-plugin-rewire and babel-plugin-istanbul but all suggestions in those threads does not work for me.

I have a repo set up with my changes if someone wants to dig deeper since I don't get any further. It is a fork of react-boilerplate with newer versions of react, PhantomJS instead of Chrome and babel-plugin-rewire. https://github.com/olabalboa/react-boilerplate

The error I get is
``` 
30 11 2016 15:23:02.776:ERROR [coverage]: TypeError: Cannot read property 'start' of undefined
    at /home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:276:32
    at Array.forEach (native)
    at annotateBranches (/home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:255:30)
    at HtmlReport.writeDetailPage (/home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:426:9)
    at /home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:489:26
    at SyncFileWriter.writeFile (/home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.writeFile (/home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:488:24
    at Array.forEach (native)
    at HtmlReport.writeFiles (/home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:482:23)
    at /home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:484:22
    at Array.forEach (native)
    at HtmlReport.writeFiles (/home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:482:23)
    at HtmlReport.writeReport (/home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:566:14)
    at LcovReport.writeReport (/home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/lcov.js:55:19)
    at writeReport (/home/a168298/repos/react-boilerplate/node_modules/karma-coverage/lib/reporter.js:68:16)
```

**Comment by gihrig** [comment]
Rewire has been discussed at length here, please search the repo (issues and PRs) for "rewire", specifically #923.

**Comment by superzadeh** [comment]
Runnin into the same problem, I'll update if I find an issue

**Comment by priyajeet** [comment]
Also see https://github.com/speedskater/babel-plugin-rewire/issues/148
