### ISSUE TITLE
npm run setup failing

### ISSUE THREAD

**Issue by Patrax** [mxstbr/react-boilerplate#1375]
After cloning, trying to follow the README running `npm run setup` .

```
> react-boilerplate@3.3.3 setup /Users/patriciojeri/Sites/react-boilerplate
> node ./internals/scripts/setup.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/patriciojeri/Sites/react-boilerplate/internals/scripts/setup.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.3.3 setup: `node ./internals/scripts/setup.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.3.3 setup script 'node ./internals/scripts/setup.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./internals/scripts/setup.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.
```
- Node: v6.9.2
- NPM: 3.10.9

**Comment by Patrax** [comment]
FIX: If you followed the instructions from http://www.reactboilerplate.com/ like me, you need to clone with `git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git` instead of `git clone git@github.com:mxstbr/react-boilerplate` and then `npm run setup` works.

**Comment by iwoork** [comment]
I get the same issue and cant run it from a fresh clone.

**Comment by gihrig** [comment]
@iwoork Try `yarn install` (or `npm install`) in place of `npm run setup`. That won't clean the git repo from your clone, but otherwise it's the same.

**Comment by iwoork** [comment]
I'm getting Could not find or load main class install when I try to use yarn.

**Comment by iwoork** [comment]
Found the problem. npm needs to be updated.
