### ISSUE TITLE
Build broken on Travis with eslint@5.0.0-beta6

### ISSUE THREAD

**Issue by jbinto** [mxstbr/react-boilerplate#141]
https://travis-ci.org/jbinto/react-boilerplate/builds/106398490

https://github.com/babel/babel-eslint/issues/243

```
TypeError: Cannot read property 'visitClass' of undefined
    at monkeypatch (/home/travis/build/mxstbr/react-boilerplate/node_modules/babel-eslint/index.js:220:40)
    at Object.exports.parse (/home/travis/build/mxstbr/react-boilerplate/node_modules/babel-eslint/index.js:362:5)
    at parse (/home/travis/build/mxstbr/react-boilerplate/node_modules/eslint/lib/eslint.js:512:27)
    at EventEmitter.module.exports.api.verify (/home/travis/build/mxstbr/react-boilerplate/node_modules/eslint/lib/eslint.js:646:19)
    at processText (/home/travis/build/mxstbr/react-boilerplate/node_modules/eslint/lib/cli-engine.js:230:27)
    at processFile (/home/travis/build/mxstbr/react-boilerplate/node_modules/eslint/lib/cli-engine.js:270:18)
    at executeOnFile (/home/travis/build/mxstbr/react-boilerplate/node_modules/eslint/lib/cli-engine.js:617:23)
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/home/travis/build/mxstbr/react-boilerplate/node_modules/eslint/lib/cli-engine.js:640:56)
    at Object.cli.execute (/home/travis/build/mxstbr/react-boilerplate/node_modules/eslint/lib/cli.js:162:95)
```

**Comment by jbinto** [comment]
Fixed in https://github.com/jbinto/react-boilerplate/commit/44dd0cf32fb4b052653a7e3cb21d76c016bdf59d, but build is still failing.

**Comment by mxstbr** [comment]
This issue is fixed for now!
