### ISSUE TITLE
npm run setup acts abnormally !

### ISSUE THREAD

**Issue by MehdiRaash** [mxstbr/react-boilerplate#1443]
Hello
npm run setup does not work properly. and throws this error:

    module.js:471 
    throw err;
    ^ 
    Error: Cannot find module 'lodash/defaultsDeep'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mytest/react-boilerplate/internals/scripts/dependencies.js:13:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

I continued (and luckily problem has been solved by...)

**1 . npm install**
**2 . npm run build:dll**
I then run **npm run start** again I got error like:

     Localhost: http://localhost:3000
      LAN: http://x.x.x.x:3000
    ----------------------------------
    Press CTRL-C to stop

    webpack built ca8e75bb083c3250f9b5 in 11355ms

    ERROR in ./app/components/Header/banner.jpg
    Module build failed: Error: spawn /home/mytest/react-boilerplate/node_modules/jpegtran-             bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
     @ ./app/components/Header/index.js 47:0-34
     @ ./app/containers/App/index.js
     @ ./app/app.js
     @ multi main
    Child html-webpack-plugin for "index.html":
**3.npm rb**  after that **problem has been solved** 

But the thing is I'm a bit worried for production...
Why that happened?
Why does not boilerplate just install by **npm run setup**?

NodeJS v.6.9.2 
NPM v4.0.5 
on a fresh Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-57-generic x86_64).

**Comment by gihrig** [comment]
Not sure what to say about your issues. But I have had much better results installing with [Yarn](https://yarnpkg.com/en/docs/install#linux-tab).

`yarn install` will do everything `npm run setup` does except delete and refresh the local Github repo.

Try that and see what happens.

I have not tried npm 4.x

**Comment by MehdiRaash** [comment]
Thanks, I just installed more than 10 react plus etc boilerplate today, simply from their instructions suggests. 
Just 2 of them **won** this champion!
Actually those 2 were **less** than 1k starts!
