### ISSUE TITLE
webpack.base.babel.js bug when running npm run build

### ISSUE THREAD

**Issue by learntoswim** [mxstbr/react-boilerplate#246]
Came across a very strange bug when running

`npm run build`

Basically, in the file `./internals/webpack/webpack.base.babel.js` if you set the property `stats` to `true` you will see the following:

```
  devtool: options.devtool,
  target: 'web', // Make web variables accessible to webpack, e.g. window
  stats: true,  // Don't show stats in the console <--- this is the line 
  progress: true,
```

Results in

```
> reactjs-boilerplate@2.4.0 build /Users/xxxx/reactjs-boilerplate
> cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --colors -p

/Users/xxxx/reactjs-boilerplate/node_modules/webpack/bin/webpack.js:63
	var outputOptions = Object.create(options.stats || firstOptions.stats || {});
	                           ^

TypeError: Object prototype may only be an Object or null: true
    at Function.create (native)
    at processOptions (/Users/xxxx/reactjs-boilerplate/node_modules/webpack/bin/webpack.js:63:29)
    at Object.<anonymous> (/Users/xxxx/reactjs-boilerplate/node_modules/webpack/bin/webpack.js:192:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

I'm having trouble finding what this option does. Any clues?

**Comment by 7rulnik** [comment]
Seems like options.stats must be an object.
Try something like this:
```
stats: {
  // Config for minimal console.log mess.
  assets: false,
  colors: true,
  version: false,
  hash: false,
  timings: false,
  chunks: false,
  chunkModules: false
}
```

You can find more info [here](https://github.com/webpack/docs/wiki/node.js-api#stats)

**Comment by learntoswim** [comment]
Thanks @7rulnik. Just a note; I realize that this is not an issue for this boilerplate, but it is set to `false` as a default, which may confuse people moving forward.

**Comment by 7rulnik** [comment]
Maybe we should add comment with link to possible options

**Comment by learntoswim** [comment]
Certainly. I think there are major learning curves associated with this boilerplate, so any further documentation would be great.

**Comment by mxstbr** [comment]
We're working on it over at #227, let us know what else you'd like documented there!
