### ISSUE TITLE
[v3.0.0] Server fails to start on node 5

### ISSUE THREAD

**Issue by webdesserts** [mxstbr/react-boilerplate#269]
I tried installing and running `npm start` with node 5 on Ubuntu 14.0.4 and got the following error

```
michael@charon
 ~/code/react-boilerplate> npm start

> reactjs-boilerplate@2.4.0 start /home/michael/code/react-boilerplate
> npm run start:tunnel


> reactjs-boilerplate@2.4.0 start:tunnel /home/michael/code/react-boilerplate
> cross-env NODE_ENV=development node server

module.js:341
    throw err;
    ^

Error: Cannot find module '../features'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/michael/code/react-boilerplate/node_modules/caniuse-api/dist/index.js:19:32)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/michael/code/react-boilerplate/node_modules/postcss-cssnext/lib/index.js:11:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start:tunnel"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! reactjs-boilerplate@2.4.0 start:tunnel: `cross-env NODE_ENV=development node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactjs-boilerplate@2.4.0 start:tunnel script 'cross-env NODE_ENV=development node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the reactjs-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs reactjs-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls reactjs-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/michael/code/react-boilerplate/npm-debug.log

npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! reactjs-boilerplate@2.4.0 start: `npm run start:tunnel`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactjs-boilerplate@2.4.0 start script 'npm run start:tunnel'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the reactjs-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run start:tunnel
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs reactjs-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls reactjs-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/michael/code/react-boilerplate/npm-debug.log
```

If I swap to node v4.4.2 (npm 2.15.0) all is well

**Comment by webdesserts** [comment]
Ok, something else fishy might be happening here. It seems that the initial install fails no matter what version I'm on, but will succeed after an `npm rebuild`

**Comment by webdesserts** [comment]
I'm going to close this for now as I'm 90% sure it's an issue with my setup. I'll reopen if I find out otherwise.

**Comment by mxstbr** [comment]
Nice, thanks so much!

**Comment by andrewleith** [comment]
I see the exact same thing on windows, node v5.11.0.  `npm rebuild` does not solve it for me.

**Comment by morajabi** [comment]
Me too. on osx 10.11.x

**Comment by 7rulnik** [comment]
@morajabi `Error: listen EADDRINUSE :::3000` tells that you already have process on 3000 port.
Maybe this link will help you
http://stackoverflow.com/questions/4075287/node-express-eaddrinuse-address-already-in-use-kill-server
