### ISSUE TITLE
Problem linting CSS

### ISSUE THREAD

**Issue by thijsw** [mxstbr/react-boilerplate#320]
I checked out the project, run the setup. Then, when I run the command `npm run test` (which calls `npm run lint:css`) it fails when compiling the css files.

```
app/components/A/styles.css
 2:10  ✖  Expected "ADDD" to be "addd"      unit-case
 2:10  ✖  Unexpected unknown unit "ADDD"    unit-no-unknown
 6:10  ✖  Expected "CC0E5" to be "cc0e5"    unit-case
 6:10  ✖  Unexpected unknown unit "CC0E5"   unit-no-unknown

app/components/Button/styles.css
 24:21  ✖  Expected "ADDD" to be "addd"     unit-case

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "run" "lint:css"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 lint:css: `stylelint ./app/**/*.css`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the react-boilerplate@3.0.0 lint:css script 'stylelint ./app/**/*.css'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     stylelint ./app/**/*.css
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/thijs/Projects/react-boilerplate/npm-debug.log

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 lint: `npm run lint:js && npm run lint:css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.0.0 lint script 'npm run lint:js && npm run lint:css'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint:js && npm run lint:css
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/thijs/Projects/react-boilerplate/npm-debug.log

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 pretest: `npm run lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.0.0 pretest script 'npm run lint'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/thijs/Projects/react-boilerplate/npm-debug.log
```

**Comment by mxstbr** [comment]
Oh no, that's definitely not intended! I'd much appreciate a PR fixing this.

**Comment by DonHansDampf** [comment]
Same here on a new clone without any changed files on MacOS El Capitan. NPM and Nodejs up2date.

**Comment by jahvi** [comment]
Works fine for me on MacOS El Capitan, node v5.10.1 and npm 3.8.6. I wonder if you're trying to run the global stylelint instead of the locally installed one so the correct rules are not getting loaded.

What happens if you run `./node_modules/.bin/stylelint ./app/**/*.css` from the project directory?

**Comment by DonHansDampf** [comment]
I get this output:
```
➜  react-boilerplate git:(master) ./node_modules/.bin/stylelint ./app/**/*.css
Error: Files glob patterns specified did not match any files
    at /Users/marcel/dev/react-boilerplate/node_modules/stylelint/dist/standalone.js:47:17
    at run (/Users/marcel/dev/react-boilerplate/node_modules/core-js/modules/es6.promise.js:89:22)
    at /Users/marcel/dev/react-boilerplate/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/Users/marcel/dev/react-boilerplate/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
```

**Comment by jwinn** [comment]
@DonHansDampf is this after running `npm run clean`? -- which is expected because `clean` removes all style files

**Comment by DonHansDampf** [comment]
@jwinn indeed. I cloned the repo again, and tried the comment again after `npm run setup` and it worked without an error. 
Of course the test fails without a css file. My bad.

**Comment by jwinn** [comment]
It's not your bad :-D. Just `stylelint` doesn't allow for ignoring/warning (instead of erroring out) if there are no matching files.

**Comment by VinSpee** [comment]
No problem here either - i think this is a false alarm.

**Comment by mxstbr** [comment]
Will close since it seems to be the case of simply not having any styles, which stylelint can't handle. Thanks everyone!
