### ISSUE TITLE
3.0.0 - Build script throwing errors

### ISSUE THREAD

**Issue by jespersultan** [mxstbr/react-boilerplate#345]
I am unable to build a fresh project using `npm run build`

Tried building a completely fresh project
`git clone ...`
`npm run setup`
`npm run clean`
`npm run build`

Tried Node 5.11, Node 6.2, latest npm, running OS X 10.11.4

npm-debug
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.2.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.9.2
3 info using node@v6.2.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle react-boilerplate@3.0.0~prebuild: react-boilerplate@3.0.0
6 verbose lifecycle react-boilerplate@3.0.0~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle react-boilerplate@3.0.0~prebuild: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/jesper/Sites/react-boilerplate/node_modules/.bin:/usr/local/Cellar/node/6.2.0/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
8 verbose lifecycle react-boilerplate@3.0.0~prebuild: CWD: /Users/jesper/Sites/react-boilerplate
9 silly lifecycle react-boilerplate@3.0.0~prebuild: Args: [ '-c', 'npm run test && npm run build:clean' ]
10 silly lifecycle react-boilerplate@3.0.0~prebuild: Returned: code: 1  signal: null
11 info lifecycle react-boilerplate@3.0.0~prebuild: Failed to exec prebuild script
12 verbose stack Error: react-boilerplate@3.0.0 prebuild: `npm run test && npm run build:clean`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:850:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
13 verbose pkgid react-boilerplate@3.0.0
14 verbose cwd /Users/jesper/Sites/react-boilerplate
15 error Darwin 15.4.0
16 error argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "run" "build"
17 error node v6.2.0
18 error npm  v3.9.2
19 error code ELIFECYCLE
20 error react-boilerplate@3.0.0 prebuild: `npm run test && npm run build:clean`
20 error Exit status 1
21 error Failed at the react-boilerplate@3.0.0 prebuild script 'npm run test && npm run build:clean'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the react-boilerplate package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm run test && npm run build:clean
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs react-boilerplate
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls react-boilerplate
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
```

**Comment by mxstbr** [comment]
Can you give me the output you get when running `npm run test` and `npm run build:clean` individually?

*I suspect this is due to `stylelint` not linting if you have no `.css` files (which the cleaned version doesn't), see #320.*

**Comment by jespersultan** [comment]
You're right. Adding a single CSS file fixed it. 

Thanks for the quick response!

**Comment by mxstbr** [comment]
Awesome, great to hear! :+1:

**Comment by freddiehonohan** [comment]
@natlus I have run into this same problem, could you tell me where did you need to create an empty CSS file?

**Comment by natlus** [comment]
@freddiehonohan Adding any .css file should keep stylelint happy. So an `index.css` in `/src` should work

**Comment by freddiehonohan** [comment]
Thank you very much for this 👍
