### ISSUE TITLE
Server isn't compatible with Node v0.12

### ISSUE THREAD

**Issue by chappydboz** [mxstbr/react-boilerplate#349]
hey guys, first time trying to run the boilerplate.. im on osx yosemite. 
i got thru the npm install.. but here is the console output after i run "npm start":

```
> react-boilerplate@3.0.0 start /Shared/www/tacotown/tacofinder/react-site
> npm run start:tunnel


> react-boilerplate@3.0.0 start:tunnel /Shared/www/tacotown/tacofinder/react-site
> cross-env NODE_ENV=development node server

/Shared/www/tacotown/tacofinder/react-site/server/index.js:25
app.listen(port, (err) => {
                       ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "start:tunnel"
npm ERR! node v0.12.4
npm ERR! npm  v3.9.2
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 start:tunnel: `cross-env NODE_ENV=development node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.0.0 start:tunnel script 'cross-env NODE_ENV=development node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Shared/www/tacotown/tacofinder/react-site/npm-debug.log

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.4
npm ERR! npm  v3.9.2
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 start: `npm run start:tunnel`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.0.0 start script 'npm run start:tunnel'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run start:tunnel
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Shared/www/tacotown/tacofinder/react-site/npm-debug.log
```

**Comment by mxstbr** [comment]
Good catch! :+1:

This is happening because you're on Node v0.12, which doesn't have support for arrow functions apparently.
I'd suggest upgrading to one of the latest releases (`5.x` or `6.x`) to fix this for now, and we can look into making the server 0.12 compatible!

**Comment by chappydboz** [comment]
issue resolved. thanks!

**Comment by Aweary** [comment]
@mxstbr so I've got a branch working that supports 0.12, but I'm wondering if we should just add an `"engines"` section to the `package.json` requiring `>0.12`. 

I think supporting the 3 latests major versions (4, 5, 6) is reasonable, especially since this repo is intended to be used with *new* projects, so the idea of legacy support is not really applicable.

Otherwise we'd need to either add a bunch of linter exceptions or adjust the linting requirements, because you get a bunch of errors like this now:

<img width="837" alt="screen shot 2016-05-21 at 4 44 30 pm" src="https://cloud.githubusercontent.com/assets/6886061/15450984/ba3eb450-1f73-11e6-94de-405a28286952.png">

**Comment by grabbou** [comment]
I think you can also suggest using `babel-node` kind of thing (or require hook) for all these that need to support 0.12.x. Since the current state of the node app is to just server the content, transpilation is not going to add any maintenance overheat (that would be the case with bigger apps)

**Comment by Aweary** [comment]
I think that's fair :+1:

**Comment by mxstbr** [comment]
That sounds very reasonable. Let's add a page to the docs explaining how to use `babel-node`!

**Comment by eddiewang** [comment]
instead of 'babel-node', I suggest using 'babel-watch', it's kind of like nodemon and babel-node combined!
