### ISSUE TITLE
Startup problem

### ISSUE THREAD

**Issue by mitajunior** [mxstbr/react-boilerplate#389]
Clone the repo
npm run setup - success
npm start

Error: no such file or directory
   at MemoryFileSystem.readFileSync (C:\Users\oscar\projects\support-engine-ui\node_modules\memory-fs\lib\MemoryFileSystem.js:107:10)
   at C:\Users\oscar\projects\support-engine-ui\server\middlewares\frontendMiddleware.js:25:21
   at Layer.handle [as handle_request] (C:\Users\oscar\projects\support-engine-ui\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\Users\oscar\projects\support-engine-ui\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (C:\Users\oscar\projects\support-engine-ui\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (C:\Users\oscar\projects\support-engine-ui\node_modules\express\lib\router\layer.js:95:5)
   at C:\Users\oscar\projects\support-engine-ui\node_modules\express\lib\router\index.js:277:22
   at param (C:\Users\oscar\projects\support-engine-ui\node_modules\express\lib\router\index.js:349:14)
   at param (C:\Users\oscar\projects\support-engine-ui\node_modules\express\lib\router\index.js:365:14)
   at Function.process_params (C:\Users\oscar\projects\support-engine-ui\node_modules\express\lib\router\index.js:410:3)
   at next (C:\Users\oscar\projects\support-engine-ui\node_modules\express\lib\router\index.js:271:10)
   at middleware (C:\Users\oscar\projects\support-engine-ui\node_modules\webpack-hot-middleware\middleware.js:39:48)
   at Layer.handle [as handle_request] (C:\Users\oscar\projects\support-engine-ui\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (C:\Users\oscar\projects\support-engine-ui\node_modules\express\lib\router\index.js:312:13)
   at C:\Users\oscar\projects\support-engine-ui\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (C:\Users\oscar\projects\support-engine-ui\node_modules\express\lib\router\index.js:330:12)

**Comment by mwksl** [comment]
@mitajunior try running `npm install` and see if that allows you to run the server. I've had that issue on new instances of the boilerplate and that seems to fix it. Let me know if that works.

**Comment by mxstbr** [comment]
It definitely looks like a problem in your environment, it works fine on my local machine. Closing for now, feel free to comment again if you run into more specific problems!

**Comment by gkoberger** [comment]
@mxstbr I'm getting this same problem. Brand new OSX machine, and I followed the directions. Have you tried installing `react-boilerplate` recently?

**Comment by mxstbr** [comment]
Oh damn, must've been on a stale version, that's happening for me! Reopening, thanks for commenting @gkoberger, fixing asap!

**Comment by mxstbr** [comment]
Fixed, sorry for the troubles!

**Comment by gkoberger** [comment]
Thanks @mxstbr!
