### ISSUE TITLE
"Error: Path app/components/A/index.js was not found" on 'npm run clean'

### ISSUE THREAD

**Issue by padurean** [mxstbr/react-boilerplate#448]
Latest code, pulled few minutes ago:

```
~/w/g/j/react-boilerplate (master) λ npm run clean

> react-boilerplate@3.0.0 clean /Users/ogg/ws/github/js/react-boilerplate
> shjs ./internals/scripts/clean.js

Cleanup started... ✓Running eslint on git staged files: **/*.@(js|jsx)
Running jscs on git staged files: **/*.@(js|jsx)
Error: Path app/components/A/index.js was not found.
    at .<anonymous> (/Users/ogg/ws/github/js/react-boilerplate/node_modules/jscs/lib/checker.js:188:19)
    at Array.<anonymous> (/Users/ogg/ws/github/js/react-boilerplate/node_modules/vow/lib/vow.js:712:39)
    at Immediate.callFns [as _onImmediate] (/Users/ogg/ws/github/js/react-boilerplate/node_modules/vow/lib/vow.js:23:35)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `lint:staged`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit: 

Error: Git commit failed
```

**Comment by mxstbr** [comment]
Dang, that's annoying! Highly likely because of #431, @FezVrasta would you mind looking into this?

**Comment by kunal-mandalia** [comment]
Hi @padurean , try it again with the latest clone. A PR has been merged to deal with this #449 . I cloned a fresh copy a couple of mins ago, ran setup and clean , no issues 💯

**Comment by mxstbr** [comment]
Yeah, this is fixed! Sorry for the troubles!

**Comment by padurean** [comment]
Thanks guys - i can confirm the issue is fixed now.
