### ISSUE TITLE
Error during fresh `npm run`

### ISSUE THREAD

**Issue by blissdev** [mxstbr/react-boilerplate#467]
After following the instructions in the README and running `npm run` I get the following error:

```
⋊> ~/d/e/react-boilerplate on master ◦ npm start                                                                                                                                                        13:27:23

> react-boilerplate@3.0.0 start /Users/bliss/dev/etc/react-boilerplate
> npm run start:tunnel


> react-boilerplate@3.0.0 start:tunnel /Users/bliss/dev/etc/react-boilerplate
> cross-env NODE_ENV=development node server

Server started ✓
Tunnel initialised ✓

Access URLs:
-----------------------------------
Localhost: http://localhost:3000
      LAN: http://192.168.1.39:3000
    Proxy: https://e60ee660.ngrok.io
-----------------------------------
Press CTRL-C to stop

webpack built 62e83b007e030e2719e5 in 14375ms

ERROR in ./app/containers/App/banner-metal.jpg
Module parse failed: /Users/bliss/dev/etc/react-boilerplate/app/containers/App/banner-metal.jpg Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./app/containers/App/index.js 16:0-40
Child html-webpack-plugin for "index.html":
```

If I try to access localhost:3000 I get:

```
Error: no such file or directory
    at MemoryFileSystem.readFileSync (/Users/bliss/dev/etc/react-boilerplate/node_modules/memory-fs/lib/MemoryFileSystem.js:107:10)
    at app.get (/Users/bliss/dev/etc/react-boilerplate/server/middlewares/frontendMiddleware.js:26:21)
    at Layer.handle [as handle_request] (/Users/bliss/dev/etc/react-boilerplate/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/bliss/dev/etc/react-boilerplate/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/bliss/dev/etc/react-boilerplate/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/bliss/dev/etc/react-boilerplate/node_modules/express/lib/router/layer.js:95:5)
    at /Users/bliss/dev/etc/react-boilerplate/node_modules/express/lib/router/index.js:277:22
    at param (/Users/bliss/dev/etc/react-boilerplate/node_modules/express/lib/router/index.js:349:14)
    at param (/Users/bliss/dev/etc/react-boilerplate/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/bliss/dev/etc/react-boilerplate/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/bliss/dev/etc/react-boilerplate/node_modules/express/lib/router/index.js:271:10)
    at middleware (/Users/bliss/dev/etc/react-boilerplate/node_modules/webpack-hot-middleware/middleware.js:39:48)
    at Layer.handle [as handle_request] (/Users/bliss/dev/etc/react-boilerplate/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/bliss/dev/etc/react-boilerplate/node_modules/express/lib/router/index.js:312:13)
    at /Users/bliss/dev/etc/react-boilerplate/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/bliss/dev/etc/react-boilerplate/node_modules/express/lib/router/index.js:330:12)
```

Versions:
Node: 6.2.1
NPM: 3.9.3
OS: OS X 10.11.4

**Comment by mxstbr** [comment]
Fixed in an hour ago in e60409929a458e695a4d5e4da27628a6fe891fa0! Take a fresh pull from master and everything is going to work again!

**Comment by blissdev** [comment]
Thanks it did, sorry about that.

**Comment by Axighi** [comment]
@mxstbr I just pulled the master, the problem still exists.

**Comment by gihrig** [comment]
@Axighi Sorry to here you're having trouble!

Please, try:
- `npm cache clean`
- Delete your failed react-boilerplate directory
- make a new clone and run `npm run setup`

If the problem persists:

Please tell us about your system
- OS and Version.
- The the exact command you are running.
- A full screen/error dump.

I just completed a fresh clone and `npm run setup` without error.
Mac OS 10.22.5
Node 5.8.0
npm 3.8.2

**Comment by Axighi** [comment]
@gihrig I did it again. It now works fine. I believe it's related to cnpm I previously used to install the dependencies. So here I recommend all the developer in China use original npm repo via VPN.

**Comment by gihrig** [comment]
OK, I didn't know about cnpm. Glad you got it working.

**Comment by sourcesoft** [comment]
Today when I get a new fresh clone and run setup, I get the exact same error when `npm start`.
How is it that it's not fixed for me yet? I ran all:
`npm cache clean`
`git clone https://github.com/mxstbr/react-boilerplate.git`
`npm start`
```
Access URLs:
-----------------------------------
Localhost: http://localhost:3000
      LAN: http://192.168.43.128:3000
-----------------------------------
Press CTRL-C to stop
    
webpack built 3dc0ce3390f3fab19112 in 6114ms

ERROR in ./app/containers/App/banner-metal.jpg
Module build failed: Error: spawn /Users/Pooya/Documents/Projects/temp/react-boilerplate/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:1012:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./app/containers/App/index.js 17:0-40
Child html-webpack-plugin for "index.html":
```

npm 3.10.3
node v6.3.1
on mac

**Comment by gihrig** [comment]
@sourcesoft 
see [#769 (comment)](https://github.com/mxstbr/react-boilerplate/issues/769#issuecomment-235060318) and continuing.

Let us know if that does not help.

**Comment by jose920405** [comment]
hi @gihrig inside [#769 (comment)](https://github.com/react-boilerplate/react-boilerplate/issues/769#issuecomment-235060318) is a topic for windows 7 and many varied errors. I would like to ask you to please pay attention to this case right here..

The problem still happening for me in osx.

I have tried running this test project on 2 macs and 1 pc with linux failing only on 1 of the macs.

My problem is the same.


```
ERROR in ./app/containers/App/banner-metal.jpg
Module build failed: Error: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/vovsolution/Documents/git-repos/dev-web-react/colombo-web-payments/node_modules/mozjpeg/vendor/cjpeg
  Reason: image not found

    at Promise.all.then.arr (/Users/vovsolution/Documents/git-repos/dev-web-react/colombo-web-payments/node_modules/exec-buffer/node_modules/execa/index.js:201:11)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
 @ ./app/containers/App/index.tsx 27:13-42
 @ ./app/app.tsx
 @ multi eventsource-polyfill webpack-hot-middleware/client ./app/app.tsx
```

Resulting in the following error on page

![captura de pantalla 2017-09-15 a la s 10 21 03 a m](https://user-images.githubusercontent.com/12536184/30490469-a93e5414-99ff-11e7-82ff-21ddb60ea5c7.png)
