### ISSUE TITLE
Errors building app in Windows

### ISSUE THREAD

**Issue by eddiewang** [mxstbr/react-boilerplate#540]
Getting errors trying to run the application. Any Windows developers know how to debug this issue?

```
> react-boilerplate@3.0.0 start C:\Users\wange\Desktop\dev\react-boilerplate
> cross-env NODE_ENV=development node server

module.js:339
    throw err;
    ^

Error: Cannot find module '../features'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\wange\Desktop\dev\react-boilerplate\node_modules\caniuse-api\dist\index.js:19:32)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\wange\Desktop\dev\react-boilerplate\node_modules\postcss-cssnext\lib\index.js:11:19)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.2.0
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 start: `cross-env NODE_ENV=development node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.0.0 start script 'cross-env NODE_ENV=development node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\wange\Desktop\dev\react-boilerplate\npm-debug.log

```

**Comment by eddiewang** [comment]
and when performing an npm install directly...
```
$ npm install

> node-sass@3.7.0 install C:\Users\wange\Desktop\dev\react-boilerplate\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at C:\Users\wange\Desktop\dev\react-boilerplate\node_modules\node-sass\vendor\win32-x-46\binding.node

> node-sass@3.7.0 postinstall C:\Users\wange\Desktop\dev\react-boilerplate\node_modules\node-sass
> node scripts/build.js

"C:\Users\wange\Desktop\dev\react-boilerplate\node_modules\node-sass\vendor\win32-x64-46\binding.node" exists.
 testing binary.
Binary is fine; exiting.

> react-boilerplate@3.0.0 preinstall C:\Users\wange\Desktop\dev\react-boilerplate
> npm run npmcheckversion


> react-boilerplate@3.0.0 npmcheckversion C:\Users\wange\Desktop\dev\react-boilerplate
> node ./internals/scripts/npmcheckversion.js


npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "n" "npmcheckversion"
npm ERR! node v4.2.0
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 npmcheckversion: `node ./internals/scripts/npmcheckversion.js`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the react-boilerplate@3.0.0 npmcheckversion script 'node ./internals/scripts/npmcheckversion.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./internals/scripts/npmcheckversion.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\wange\Desktop\dev\react-boilerplate\npm-debug.log

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN karma-webpack@1.7.0 requires a peer of webpack@^1.4.0 but none was installed.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "stall"
npm ERR! node v4.2.0
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 preinstall: `npm run npmcheckversion`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.0.0 preinstall script 'npm run npmcheckversion'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run npmcheckversion
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\wange\Desktop\dev\react-boilerplate\npm-debug.log

```

**Comment by mmaedel** [comment]
hello eddie
seems like dev_env (Make sure you have the latest version of node.js and npm installed.) problems..

It took me quite a while to have stable node running on windows...

follow: https://github.com/Microsoft/nodejs-guidelines

btw. i use the chakracore

all the best

**Comment by mmaedel** [comment]
and this of course: https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/faq.md

**Comment by eddiewang** [comment]
Figured it out - the culprit was webpack-image-loader. The issue revolves around needing admin privileges to install the app.

**Comment by mxstbr** [comment]
>  the culprit was webpack-image-loader.

Could you elaborate a bit? Will this affect other people, or was this an environment specific problem? Should we remove `webpack-image-loader` and/or submit an issue there?

**Comment by eddiewang** [comment]
@mxstbr it shouldn't affect people unless they're working in a corporate environment. I work at a pension fund, so they take security very seriously. One of the dependencies in webpack-image-loader, pngquant executes an .exe that requires admin privileges in order to work. My privileges are not that high, so the npm install did not run through correctly.

I don't think it should be a problem for most computers - I removed the webpack image loader from my build just because I don't have a huge need for it, and it would be a pain to develop at work should the library stay in package.json.

**Comment by mxstbr** [comment]
Ah, alright, fair enough! Glad you figured out out!
