### ISSUE TITLE
Cannot run setup

### ISSUE THREAD

**Issue by Siraris** [mxstbr/react-boilerplate#574]
Just cloned this repo, whenever I run npm run setup I get:

```
> react-boilerplate@3.0.0 presetup /Library/WebServer/Documents/react-boilerplate
> npm i chalk

chalk@1.1.3 node_modules/chalk
├── ansi-styles@2.2.1
├── escape-string-regexp@1.0.5
├── supports-color@2.0.0
├── has-ansi@2.0.0 (ansi-regex@2.0.0)
└── strip-ansi@3.0.1 (ansi-regex@2.0.0)

> react-boilerplate@3.0.0 setup /Library/WebServer/Documents/react-boilerplate
> node ./internals/scripts/setup.js


Cleaning old repository ✓
Installing dependencies. ✓ (This might take a while)Installing dependencies
Initialising new repository ✓
Done!
> react-boilerplate@3.0.0 postsetup /Library/WebServer/Documents/react-boilerplate
> npm run build:dll


> react-boilerplate@3.0.0 build:dll /Library/WebServer/Documents/react-boilerplate
> node ./internals/scripts/dependencies.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Library/WebServer/Documents/react-boilerplate/internals/scripts/dependencies.js:8:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

At this point, it also deletes most of the setup files, so I can't even run setup again.  Any ideas?

**Comment by eddiewang** [comment]
try npm install first - I find that fixed alot of errors.

**Comment by Siraris** [comment]
Figured it out - my NPM was out of date.  Might want to update the readme to indicate npm install npm -g is a good idea before running the script.  

Might also want to check into the flow to prevent it from deleting vital files if it fails :)
