### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by gvhuyssteen** [mxstbr/react-boilerplate#644]
I know this issue have been opened before and closed, but none of the advice helped me.

The error I'm getting when running **_npm start_**:
```
$ npm start

> react-boilerplate@3.0.0 start /Users/{user}/www/lolpbp/client
> cross-env NODE_ENV=development node server

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at EventEmitter.listen (/Users/{user}/www/lolpbp/client/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/{user}/www/lolpbp/client/server/index.js:26:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.1
npm ERR! npm  v3.10.1
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 start: `cross-env NODE_ENV=development node server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 start script 'cross-env NODE_ENV=development node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/{user}/www/lolpbp/client/npm-debug.log
```

According to other closed issues, all I needed to do was to install cross-env, which I did.

I have deleted the node_modules folder and ran **npm install** again.
The issue persisted.

I'm running:
Mac: El Cap
node: v6.2.1
npm: v3.10.1

Installation Steps:

**Step 1:** $ git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git client
**Step 2:** $ cd client
**Step 3:** $ npm run setup
**Step 4:** $ npm start
**Visual:** An error occurred.
**Step 5:** $ rm -rf node_modules
**Step 6:** $ npm install
**Step 7:** $ npm install --save cross-env
**Step 8:** $ npm start
**Visual:** Error still exists
**Step 9:** $ cross-env
**Visual:** Could not run cross-env
**Step 10:** $ npm install -g cross-env
**Step 11:** $ cross-env
**Visual:** Error disappeared
**Step 12:** $ npm start
**Visual:** My last error was dumped at the top of this post.

**Comment by Pinesy** [comment]
You have something else running at port 3000. Either check your running processes `ps -e|grep node` for any leftover processes, or change the port.

**Comment by gvhuyssteen** [comment]
Thanks,
There was nothing that was running on port 3000, but when I changed it it did work.
Thank you for your help.

**Comment by Thananjaya** [comment]
I am also suffering from the same issue. The steps that I have followed are given below,
I am using npm version 5.5.1
ubuntu version 16.04 LTE

**Step 1:** $ git clone git@github.com:react-boilerplate/react-boilerplate.git 
**Step 2:** $ sudo npm run setup
**Step 3:** $ sudo npm start
_**An error occured as shown in the above post**_
**Step 4:** $ rm -rf node_modules
**Step 5:** $sudo npm install
_**The following error occured when running step 5**_

```
sudo npm install
npm WARN lifecycle react-boilerplate@3.5.0~preinstall: cannot run in wd %s %s (wd=%s) react-boilerplate@3.5.0 npm run npmcheckversion /home/thananjaya/work/react-boilerplate/react-boilerplate
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

> pre-commit@1.2.2 install /home/thananjaya/work/react-boilerplate/react-boilerplate/node_modules/pre-commit
> node install.js

pre-commit:
pre-commit: Failed to create the hook file in your .git/hooks folder because:
pre-commit: EACCES: permission denied, open '/home/thananjaya/work/react-boilerplate/react-boilerplate/.git/hooks/pre-commit'
pre-commit: The hook was not installed.
pre-commit:
pre-commit:
pre-commit: chmod 0777 the pre-commit file in your .git/hooks folder because:
pre-commit: ENOENT: no such file or directory, chmod '/home/thananjaya/work/react-boilerplate/react-boilerplate/.git/hooks/pre-commit'
pre-commit:

> spawn-sync@1.0.15 postinstall /home/thananjaya/work/react-boilerplate/react-boilerplate/node_modules/spawn-sync
> node postinstall


> uglifyjs-webpack-plugin@0.4.6 postinstall /home/thananjaya/work/react-boilerplate/react-boilerplate/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> gifsicle@3.0.4 postinstall /home/thananjaya/work/react-boilerplate/react-boilerplate/node_modules/gifsicle
> node lib/install.js

  ⚠ EACCES: permission denied, mkdir '/home/thananjaya/work/react-boilerplate/react-boilerplate/node_modules/gifsicle/vendor'
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
/home/thananjaya/work/react-boilerplate/react-boilerplate/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				^

Error: callback() can only be called once.
    at onetime (/home/thananjaya/work/react-boilerplate/react-boilerplate/node_modules/onetime/index.js:15:11)
    at /home/thananjaya/work/react-boilerplate/react-boilerplate/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/home/thananjaya/work/react-boilerplate/react-boilerplate/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:111:20)
    at ConcatStream.emit (events.js:208:7)
    at finishMaybe (/home/thananjaya/work/react-boilerplate/react-boilerplate/node_modules/readable-stream/lib/_stream_writable.js:620:14)
    at endWritable (/home/thananjaya/work/react-boilerplate/react-boilerplate/node_modules/readable-stream/lib/_stream_writable.js:628:3)
    at ConcatStream.Writable.end (/home/thananjaya/work/react-boilerplate/react-boilerplate/node_modules/readable-stream/lib/_stream_writable.js:584:41)
    at DuplexWrapper.onend (/home/thananjaya/work/react-boilerplate/react-boilerplate/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:313:30)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@3.0.4 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gifsicle@3.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thananjaya/.npm/_logs/2018-03-21T10_59_12_461Z-debug.log

```
Is there any solutions for it!!
