### ISSUE TITLE
Problem with npm run setup

### ISSUE THREAD

**Issue by 10thfloor** [mxstbr/react-boilerplate#646]
Running the setup command results in the following errors:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'setup' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info presetup react-boilerplate@3.0.0
6 verbose unsafe-perm in lifecycle true
7 info setup react-boilerplate@3.0.0
8 verbose unsafe-perm in lifecycle true
9 info react-boilerplate@3.0.0 Failed to exec setup script
10 verbose stack Error: react-boilerplate@3.0.0 setup: `node ./internals/scripts/setup.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at EventEmitter.emit (events.js:172:7)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at ChildProcess.emit (events.js:172:7)
10 verbose stack     at maybeClose (internal/child_process.js:827:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
11 verbose pkgid react-boilerplate@3.0.0
12 verbose cwd /Users/MK/Desktop/react-boilerplate
13 error Darwin 15.5.0
14 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup"
15 error node v4.4.4
16 error npm  v2.15.1
17 error code ELIFECYCLE
18 error react-boilerplate@3.0.0 setup: `node ./internals/scripts/setup.js`
18 error Exit status 1
19 error Failed at the react-boilerplate@3.0.0 setup script 'node ./internals/scripts/setup.js'.
19 error This is most likely a problem with the react-boilerplate package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node ./internals/scripts/setup.js
19 error You can get information on how to open an issue for this project with:
19 error     npm bugs react-boilerplate
19 error Or if that isn't available, you can get their info via:
19 error
19 error     npm owner ls react-boilerplate
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by 10thfloor** [comment]
Great project! Thanks.

**Comment by gihrig** [comment]
@mxstbr This is the second recent issue caused by npm < 3 ref #574 (cannot run setup).

I notice `internals/scripts/npmcheckversion.js`, but this in not included in setup. Is there a reason for that?

If not, I would be happy to submit a PR.

**Comment by mxstbr** [comment]
Oh, I don't know why that was removed! Yeah, please submit a PR fixing that :+1:

**Comment by gihrig** [comment]
Incidentally, I'm working on improving setup UX. 

PR soon
