### ISSUE TITLE
npm run npmcheckversion failed [ERROR: React Boilerplate] You need npm version @>=3

### ISSUE THREAD

**Issue by ChihChengLiang** [mxstbr/react-boilerplate#694]
Thanks for the great project. I just want to try the `npm install`, however it stuck at the checking version. Here's what it shows when I ran `npm run npmcheckversion`

```
 $ npm run npmcheckversion

> react-boilerplate@3.0.0 npmcheckversion /home/chihchengliang/linker_networks/dashboard/react-boilerplate
> node ./internals/scripts/npmcheckversion.js

/home/chihchengliang/linker_networks/dashboard/react-boilerplate/internals/scripts/npmcheckversion.js:6
    throw new Error('[ERROR: React Boilerplate] You need npm version @>=3');
    ^

Error: [ERROR: React Boilerplate] You need npm version @>=3
    at /home/chihchengliang/linker_networks/dashboard/react-boilerplate/internals/scripts/npmcheckversion.js:6:11
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

npm ERR! Linux 3.13.0-91-generic
npm ERR! argv "/usr/bin/nodejs" "/home/chihchengliang/npm-global/bin/npm" "run" "npmcheckversion"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 npmcheckversion: `node ./internals/scripts/npmcheckversion.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 npmcheckversion script 'node ./internals/scripts/npmcheckversion.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./internals/scripts/npmcheckversion.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/chihchengliang/linker_networks/dashboard/react-boilerplate/npm-debug.log
```

**Comment by ChihChengLiang** [comment]
My environment
```
$ which npm
/home/chihchengliang/npm-global/bin/npm
$ sudo which npm
/usr/bin/npm
$ npm -v
3.10.5
$ sudo npm -v
2.15.8
```

**Comment by mxstbr** [comment]
Huh, that's weird! Does `npm run npmcheckversion` run under sudo?

**Comment by gihrig** [comment]
> $ which npm
> /home/chihchengliang/npm-global/bin/npm
> $ sudo which npm
> /usr/bin/npm
> $ npm -v
> 3.10.5
> $ sudo npm -v
> 2.15.8

Why is this a react-boilerplate bug? 

Seems to me like a user config error. Why should `sudo` invoke a different Node version?

As to `npmcheckversion` it does not specifically engage `sudo`. If it's truly a bug that problem would seem to be with the OS or `child_process`. No?

[This](http://stackoverflow.com/questions/20053251/child-process-with-impersonation) may shed some light.

from npmcheckversion
```
var exec = require('child_process').exec;
exec('npm -v', function (err, stdout, stderr) {

```

**Comment by ChihChengLiang** [comment]
It seems that I had a really messy node environments. After removed nodejs and npm and reinstall them, the installation works. For someone who might bump into the same error in the future, note that you have to check if you really removed the nodejs and npm by constantly checking `which node` and `which npm`.

Thanks @mxstbr and @gihrig for helping.
