### ISSUE TITLE
npm run setup fails

### ISSUE THREAD

**Issue by mhrisse** [mxstbr/react-boilerplate#768]
Hi guys!

Checking out this project and trying to run it, but cannot get past ```npm run setup```.
npm 3.10.3, node 6.3.0 on latest MacOS. Just cloned this on Fri Jul 22 09:55:55 2016 +0200.

Any help appreciated,
M

```
xxx:~/web/lab/pwa-test (master)$ npm run setup

> react-boilerplate@3.0.0 presetup /Users/gbrissem/Google Drive/web/lab/pwa-test
> npm i chalk

react-boilerplate@3.0.0 /Users/gbrissem/Google Drive/web/lab/pwa-test
└── chalk@1.1.3 

> react-boilerplate@3.0.0 setup /Users/xxx/Google Drive/web/lab/pwa-test
> node ./internals/scripts/setup.js

module.js:442
    throw err;
    ^

Error: Cannot find module '/Users/xxx/Google Drive/web/lab/pwa-test/internals/scripts/setup.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 setup: `node ./internals/scripts/setup.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 setup script 'node ./internals/scripts/setup.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./internals/scripts/setup.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxx/Google Drive/web/lab/pwa-test/npm-debug.log

xxx:~/web/lab/pwa-test (master)$ npm -v
*3.10.3*
xxx:~/web/lab/pwa-test (master)$ node -v
*v6.3.0*
```

**Comment by mxstbr** [comment]
Have you already run `npm run setup` before? Once you've done that you can't run it again.

**Comment by gihrig** [comment]
`Error: Cannot find module '/Users/xxx/Google Drive/web/lab/pwa-test/internals/scripts/setup`

Are you installing on `Google Drive` cloud drive? 
If so, try local. My experience with Google web services (Docs and Sheets) is they can be flakey.

**Comment by mhrisse** [comment]
Hi! Tried again with re-cloning into a new directory, not shared via drive. first run of ```npm run setup``` gives me the following (```npm-debug.log``` below as well):

```
risse:~/pwa-test (master)$ npm run setup

> react-boilerplate@3.0.0 presetup /Users/risse/pwa-test
> npm i chalk

npm http GET https://registry.npmjs.org/chalk/1.1.3
npm http 200 https://registry.npmjs.org/chalk/1.1.3
npm http GET https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz
npm http 200 https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/supports-color
npm http 200 https://registry.npmjs.org/has-ansi
npm http 200 https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz
npm http 200 https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz
npm http 200 https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz
npm http 200 https://registry.npmjs.org/supports-color
npm http 200 https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz
npm http 200 https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz
npm http 200 https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz
npm http GET https://registry.npmjs.org/ansi-regex
npm http 200 https://registry.npmjs.org/ansi-regex
chalk@1.1.3 node_modules/chalk
├── escape-string-regexp@1.0.5
├── supports-color@2.0.0
├── ansi-styles@2.2.1
├── has-ansi@2.0.0 (ansi-regex@2.0.0)
└── strip-ansi@3.0.1 (ansi-regex@2.0.0)

> react-boilerplate@3.0.0 setup /Users/risse/pwa-test
> node ./internals/scripts/setup.js


Cleaning old repository ✓
 ✓stalling dependencies... (This might take a while)Installing dependencies
Initialising new repository ✓
Done!
> react-boilerplate@3.0.0 postsetup /Users/risse/pwa-test
> npm run build:dll


> react-boilerplate@3.0.0 build:dll /Users/risse/pwa-test
> node ./internals/scripts/dependencies.js


module.js:340
    throw err;
          ^
Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/risse/pwa-test/internals/scripts/dependencies.js:8:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

npm ERR! react-boilerplate@3.0.0 build:dll: `node ./internals/scripts/dependencies.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 build:dll script.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./internals/scripts/dependencies.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.4.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "build:dll"
npm ERR! cwd /Users/risse/pwa-test
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/risse/pwa-test/npm-debug.log
npm ERR! not ok code 0

npm ERR! react-boilerplate@3.0.0 postsetup: `npm run build:dll`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 postsetup script.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:dll
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.4.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "setup"
npm ERR! cwd /Users/risse/pwa-test
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/risse/pwa-test/npm-debug.log
npm ERR! not ok code 0
risse:~/pwa-test (master)$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'setup' ]
2 info using npm@1.4.3
3 info using node@v0.10.26
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info presetup react-boilerplate@3.0.0
6 verbose unsafe-perm in lifecycle true
7 info setup react-boilerplate@3.0.0
8 verbose unsafe-perm in lifecycle true
9 info postsetup react-boilerplate@3.0.0
10 verbose unsafe-perm in lifecycle true
11 info react-boilerplate@3.0.0 Failed to exec postsetup script
12 error react-boilerplate@3.0.0 postsetup: `npm run build:dll`
12 error Exit status 1
13 error Failed at the react-boilerplate@3.0.0 postsetup script.
13 error This is most likely a problem with the react-boilerplate package,
13 error not with npm itself.
13 error Tell the author that this fails on your system:
13 error     npm run build:dll
13 error You can get their info via:
13 error     npm owner ls react-boilerplate
13 error There is likely additional logging output above.
14 error System Darwin 15.4.0
15 error command "node" "/usr/local/bin/npm" "run" "setup"
16 error cwd /Users/risse/pwa-test
17 error node -v v0.10.26
18 error npm -v 1.4.3
19 error code ELIFECYCLE
20 verbose exit [ 1, true ]
```

**Comment by gihrig** [comment]
Clean your npm cache `npm cache clean` and try again

**Comment by mhrisse** [comment]
@gihrig Still does not work after ```recloned```, ```npm cache clean```, ```npm run setup```. I am wondering what kind of setup we are doing here that is so prone to break?

```
risse:~ ()$ cd pwa-test2
risse:~/pwa-test2 (master)$ npm cache clean
risse:~/pwa-test2 (master)$ npm run setup

> react-boilerplate@3.0.0 presetup /Users/risse/pwa-test2
> npm i chalk

npm http GET https://registry.npmjs.org/chalk/1.1.3
npm http 200 https://registry.npmjs.org/chalk/1.1.3
npm http GET https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz
npm http 200 https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz
npm http GET https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/supports-color
npm http 200 https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz
npm http 200 https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz
npm http 200 https://registry.npmjs.org/ansi-styles
npm http 200 https://registry.npmjs.org/strip-ansi
npm http 200 https://registry.npmjs.org/supports-color
npm http GET https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz
npm http GET https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz
npm http GET https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz
npm http 200 https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz
npm http 200 https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz
npm http 200 https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz
npm http 200 https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz
npm http 200 https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz
npm http GET https://registry.npmjs.org/ansi-regex
npm http 200 https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.0.0.tgz
npm http 200 https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.0.0.tgz
chalk@1.1.3 node_modules/chalk
├── escape-string-regexp@1.0.5
├── supports-color@2.0.0
├── ansi-styles@2.2.1
├── has-ansi@2.0.0 (ansi-regex@2.0.0)
└── strip-ansi@3.0.1 (ansi-regex@2.0.0)

> react-boilerplate@3.0.0 setup /Users/risse/pwa-test2
> node ./internals/scripts/setup.js


Cleaning old repository ✓
 ✓stalling dependencies... (This might take a while)Installing dependencies
Initialising new repository ✓
Done!
> react-boilerplate@3.0.0 postsetup /Users/risse/pwa-test2
> npm run build:dll


> react-boilerplate@3.0.0 build:dll /Users/risse/pwa-test2
> node ./internals/scripts/dependencies.js


module.js:340
    throw err;
          ^
Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/risse/pwa-test2/internals/scripts/dependencies.js:8:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

npm ERR! react-boilerplate@3.0.0 build:dll: `node ./internals/scripts/dependencies.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 build:dll script.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./internals/scripts/dependencies.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.4.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "build:dll"
npm ERR! cwd /Users/risse/pwa-test2
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/risse/pwa-test2/npm-debug.log
npm ERR! not ok code 0

npm ERR! react-boilerplate@3.0.0 postsetup: `npm run build:dll`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 postsetup script.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:dll
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.4.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "setup"
npm ERR! cwd /Users/risse/pwa-test2
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/risse/pwa-test2/npm-debug.log
npm ERR! not ok code 0
```

**Comment by mhrisse** [comment]
In ```dependiencies.js``` there is ```require('shelljs/global')```where this shelljs node_module is listed in ```package.json``` - however, its not in ```/node_modules```, why? The is nothing beside ```chalk```in ```/node_modules```and ```npm install``just fails.

**Comment by gihrig** [comment]
All setup basically does is remove and re-create the .git folder then run the the equivalent of `npm install`.

> The is nothing beside chalk in /node_modules and npm install just fails.

Sounds like there is something wrong with npm related stuff. There is no hard requirement for `npm run setup`.

What happens if you:
- `git clone https://github.com/mxstbr/react-boilerplate.git`
- `cd react-boilerplate`
- `npm install`
- `npm start`

> npm install just fails.

If that's still happening post a new `npm-debug.log` after the above steps.

**Comment by BTBurke** [comment]
Had the same problem.  I think it's an NPM issue.  Upgrading to NPM >3 seems to have fixed it.  It was a PITA to troubleshoot at first because the setup.js script deletes itself even if NPM doesn't correctly install everything.  That seems like an anti-pattern to me.

**Comment by gihrig** [comment]
@BTBurke npm < 3 is a different problem, OP says 

> npm 3.10.3

As for

< PITA to troubleshoot at first because the setup.js script deletes itself even if NPM doesn't correctly install everything

see #760

**Comment by mhrisse** [comment]
Good morning! I have just re-installed everything and started with a clean slate, then it worked. So my guess is indeed something in my ```npm``` setup was funny. Thank you guys very much for all your help. Looking forward to explore the seed now. Keep it up!

**Comment by gihrig** [comment]
Glad to hear you got it working!

Thanks for sticking with it to a solution. 👍

**Comment by varemenos** [comment]
This happened to me as well, npm version is:

```
npm --version ↵
2.14.7
```

**Comment by 1razysha4** [comment]
ERR! Linux 4.13.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "reactjs-crud-boilerplate"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code E404

I have the following version in my laptop but it aint seem to work .
any solution?
thanks in advance.
