### ISSUE TITLE
Webpack can't build sample app on Windows 7

### ISSUE THREAD

**Issue by edoloughlin** [mxstbr/react-boilerplate#781]
After getting an error-free install on windows (see https://github.com/mxstbr/react-boilerplate/issues/769), I can't build the sample app:

```
git/react-boilerplate-latest ‹master› » npm run start
npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.3.1
npm info ok
npm info it worked if it ends with ok
npm info using npm@3.10.5
npm info using node@v6.3.1
npm info lifecycle react-boilerplate@3.0.0~prestart: react-boilerplate@3.0.0
npm info lifecycle react-boilerplate@3.0.0~start: react-boilerplate@3.0.0

> react-boilerplate@3.0.0 start C:\users\a583741\git\react-boilerplate-latest
> cross-env NODE_ENV=development node server

Server started ✓

Access URLs:
-----------------------------------
Localhost: http://localhost:3000
      LAN: http://10.132.136.151:3000
-----------------------------------
Press CTRL-C to stop

webpack built b7a79a6f75d03e38cad2 in 13799ms

ERROR in ./app/containers/App/banner-metal.jpg
Module build failed: Error: The system cannot find the path specified.

    at notFoundError (C:\Users\a\git\react-boilerplate-latest\node_modules\cross-spawn-async\lib\enoent.js:8:11)
    at verifyENOENT (C:\Users\a\git\react-boilerplate-latest\node_modules\cross-spawn-async\lib\enoent.js:43:16)
    at ChildProcess.cp.emit (C:\Users\a\git\react-boilerplate-latest\node_modules\cross-spawn-async\lib\enoent.js:30:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
 @ ./app/containers/App/index.js 17:0-40
Child html-webpack-plugin for "index.html":
```

**Comment by gihrig** [comment]
>   at notFoundError (C:\Users\a\git\react-boilerplate-latest\node_modules\cross-spawn-async\lib\enoent.js:8:11)

Still looks like npm install problems. Let's keep this on #781

**Comment by jose920405** [comment]
hi @edoloughlin 

This thread is very old, but for anyone who cares.

In my case (I work with osx), I had outdated the `libpng` module only needed to run:

`brew reinstall libpng`
