### ISSUE TITLE
Tests crashing when including AWS-SDK

### ISSUE THREAD

**Issue by miltonhultgren** [mxstbr/react-boilerplate#887]
I've recently started using [react-boilerplate][1] for one of my projects and I've run into an issue with using [AWS SDK][2].

I've tried two ways of including the AWS-SDK. 

 1. npm module that I require
 2.  a simple saved copy that I load with either a webpack script loader or a export loader

Now this works fine in the dev build (the 'bundle' process goes right and I get a useable object in my code) but when I run tests (which as I understand uses a different webpack config) I get a strange crash. 

The error output I receive is: 
Chrome 52.0.2743 (Linux 0.0.0) ERROR
Uncaught TypeError: 
Cannot convert undefined or null to object 
at webpack:///~/core-js/modules/_ctx.js:18:0 <- test-bundler.js:4284

I'm running npm version 3.10.6 with node version 4.4.7. I'm not sure how much this relates to core-js or the webpack loaders since I use the same strategy for loading other dependencies that I have locally that are not NPM modules.

Some code snippets to show how I try to include it:

    require('script!path/to/lib/aws-sdk-2.5.1.min.js');
    export default window.AWS;

    const awsSdk = require('exports?window.AWS!path/to/lib/aws-sdk-2.5.1.min.js');
    export default awsSdk;

The npm version (as described by [this][3] article)

    require('aws-sdk/dist/aws-sdk');
    const AWS = window.AWS;
    export default AWS;

  [1]: https://github.com/mxstbr/react-boilerplate/tree/master/docs
  [2]: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/index.html
  [3]: http://andrewhfarmer.com/aws-sdk-with-webpack/

**Comment by miltonhultgren** [comment]
I think I've managed to narrow down the problem to this line in test-bundler.js:
`const context = require.context('../../app', true, /^^((?!(app|reducers|routes)).)*\.js$/);`
It works (i.e. doesn't crash, runs the tests and provides me with a coverage rapport) if I replace it with:
`const context = require.context('../../app', true, /\.test.js$/);`

When I was looking at examples for the webpack Karma middleware they were only including test files in the test bundle, is there a reason for why the boilerplate project includes all JS files in the test bundle?

**Comment by miltonhultgren** [comment]
I found out that the thing that causes the error is trying to print AWS.util.Buffer. Printing AWS or AWS.util also breaks because of this but printing anything else in the SDK is fine.

The error you get is a bit bigger:
```
TypeError: Cannot convert undefined or null to object
        at toString (native)
        at Function.<anonymous> (webpack:///~/core-js/modules/_ctx.js:18:0 <- test-bundler.js:4284:15)
        at stringify (context.js:23:18)
        at stringify (context.js:64:36)
        at ContextKarma.stringify (context.js:64:36)
        at ContextKarma.log (context.js:127:24)
        at Object.localConsole.(anonymous function) [as log] (context.js:218:16)
        at new HomePage (webpack:///app/containers/HomePage/index.js:9:5155 <- test-bundler.js:43257:291)
        at ShallowComponentWrapper._constructComponentWithoutOwner (webpack:///~/react/lib/ReactCompositeComponent.js:307:0 <- test-bundler.js:57801:27)
        at ShallowComponentWrapper.mountComponent (webpack:///~/react/lib/ReactCompositeComponent.js:192:0 <- test-bundler.js:57686:21)
```

When printed in the Chrome console it prints as:
`Function #<Function>`

Which I don't quite understand but it seems to be this that causes the issue. Not quite related to the boilerplate so I'll close this.
