### ISSUE TITLE
eslint errors airbnb in atom

### ISSUE THREAD

**Issue by jt3k** [mxstbr/react-boilerplate#895]
i have folowing errors  after open any js-file

```
Error: /Users/jt3k/Work/_playground/react-boilerplate/node_modules/eslint-config-airbnb/rules/react.js: Configuration for rule "react/jsx-sort-props" is invalid: Value "data["0"].shorthandLast" has additional properties.

Referenced from: airbnb Referenced from: /Users/jt3k/Work/_playground/react-boilerplate/package.json
Error: /Users/jt3k/Work/_playground/react-boilerplate/node_modules/eslint-config-airbnb/rules/react.js:
	Configuration for rule "react/jsx-sort-props" is invalid:
	Value "data["0"].shorthandLast" has additional properties.
Referenced from: airbnb
Referenced from: /Users/jt3k/Work/_playground/react-boilerplate/package.json
    at validateRuleOptions (/usr/local/lib/node_modules/eslint/lib/config/config-validator.js:115:15)
    at /usr/local/lib/node_modules/eslint/lib/config/config-validator.js:162:13
    at Array.forEach (native)
    at Object.validate (/usr/local/lib/node_modules/eslint/lib/config/config-validator.js:161:35)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:522:19)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:391:36
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:362:28)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:529:22)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:391:36
Close All
Error: /Users/jt3k/Work/_playground/react-boilerplate/node_modules/eslint-config-airbnb/rules/react.js: Configuration for rule "react/jsx-sort-props" is invalid: Value "data["0"].shorthandLast" has additional properties.

Referenced from: airbnb Referenced from: /Users/jt3k/Work/_playground/react-boilerplate/package.json
Error: /Users/jt3k/Work/_playground/react-boilerplate/node_modules/eslint-config-airbnb/rules/react.js:
	Configuration for rule "react/jsx-sort-props" is invalid:
	Value "data["0"].shorthandLast" has additional properties.
Referenced from: airbnb
Referenced from: /Users/jt3k/Work/_playground/react-boilerplate/package.json
    at validateRuleOptions (/usr/local/lib/node_modules/eslint/lib/config/config-validator.js:115:15)
    at /usr/local/lib/node_modules/eslint/lib/config/config-validator.js:162:13
    at Array.forEach (native)
    at Object.validate (/usr/local/lib/node_modules/eslint/lib/config/config-validator.js:161:35)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:522:19)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:391:36
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:362:28)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:529:22)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:391:36
```

may be let remove airbnb config?  its config make more problem for developers

**Comment by jt3k** [comment]
```
npm install -g eslint-config-pedant
```

and change `airbnb` to `pedant` in package.json  here
```
  "eslintConfig": {
    "parser": "babel-eslint",
    "extends": "pedant",
    "env": {
```
fix this problem.

**Comment by outdooricon** [comment]
I'm also experiencing this. I don't love the solution of changing away form airbnb to solve...

**Comment by gihrig** [comment]
I use Atom with react-boilerplate and don't have this problem.

> Note: If you installed ESLint globally (using the -g flag) then you must also install eslint-config-pedant globally.
> 
> A globally-installed instance of ESLint can only use globally-installed ESLint plugins. A locally-installed ESLint can make use of both locally- and globally- installed ESLint plugins.
> 

That `npm install -g eslint-config-pedant` works suggests that you have eslint installed globally. Is that right? If so, you probably need to `npm uninstall -g eslint`, or `npm install -g ...` all the eslint related packages used in react-boilerplate.

> may be let remove airbnb config? its config make more problem for developers

While linting style is a matter preference, this project has standardized on airbnb and I don't see that changing. Still, it's nice to have an example that shows how easy it is to change to pedant.

Thanks for sharing.
