### ISSUE TITLE
Incompatible redux-immutable version: Value of argument "inputState" violates contract.

### ISSUE THREAD

**Issue by pavlin-policar** [mxstbr/react-boilerplate#954]
Upon installing the latest version of this boilerplate and running `npm run test`, the following tests failed:

```
configureStore
    ✖ "before all" hook
  asyncInjectors
    getAsyncInjectors
      ✖ "before all" hook
    helpers
      ✖ "before all" hook
```
with the following error:
```
  configureStore
    ✖ "before all" hook
      Chrome 53.0.2785 (Linux 0.0.0)
    TypeError: Value of argument "inputState" violates contract.
    
    Expected:
    ?Immutable.Map
    
    Got:
    Map {
      size: number;
      _root: void;
      __ownerID: void;
      __hash: void;
      __altered: boolean;
    }
        at webpack:///~/redux-immutable/dist/combineReducers.js:46:0 <- test-bundler.js:141306:19
        at dispatch (webpack:///~/redux/lib/createStore.js:179:0 <- test-bundler.js:68259:22)
        at createStore (webpack:///~/redux/lib/createStore.js:254:0 <- test-bundler.js:68334:3)
        at webpack:///~/redux/lib/applyMiddleware.js:38:0 <- test-bundler.js:142193:19
        at createStore (webpack:///~/redux/lib/createStore.js:65:0 <- test-bundler.js:68145:33)
        at configureStore (webpack:///app/store.js:9:2229 <- test-bundler.js:36119:734)
        at Context.<anonymous> (webpack:///app/tests/store.test.js:9:1826 <- test-bundler.js:69556:112)

```

I quickly isolated the problem to a bad version of `redux-immutable`. There is a [closed issue](https://github.com/gajus/redux-immutable/issues/38) with the same as the problem I was having. Updating the version the entry `package.json` to
```
"redux-immutable": "3.0.8",
```
fixed the problem immediately.

## Steps to reproduce

1. Clone repository: `git clone https://github.com/mxstbr/react-boilerplate.git`
2. Install dependencies: `npm run setup`
3. Run tests: `npm run test`

# Versions

- Node: 6.5.0
- NPM: 3.10.6

**Comment by gihrig** [comment]
Version 3.0.2 (out soon) will contain this fix. Thanks for reporting.
