### ISSUE TITLE
Invariant Violation with generated index.test.js

### ISSUE THREAD

**Issue by lsanders** [mxstbr/react-boilerplate#995]
## Issue Type
- [x] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)
## Description

Using `npm run generate` to create a new container can lead to `Invariant Violation` exception.
## Steps to reproduce

Run `npm run generate`, select `container`. Type a container name (_DeleteMe_ in this example) and accept all defaults.

This will lead to generated `DeleteMe/tests/index.test.js` that has a starting point and uses a default import of the Container under Test:

```
// import DeleteMe from '../index';
```

If you modify the test and want to render/shallow/mount, you'll be faced with error below. You may then compare to the other index tests like `HomePage/tests/index.test.js` and miss the subtle difference.

Importing just the generated container class will resolve this error

```
// import { DeleteMe } from '../index';
```

Full error below:

```
 <DeleteMe />
    ✖ Expect to have unit tests specified
      Chromium 52.0.2743 (Ubuntu 0.0.0)
    Invariant Violation: Could not find "store" in either the context or props of "Connect(DeleteMe)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(DeleteMe)".
        at invariant (webpack:///~/invariant/browser.js:40:0 <- test-bundler.js:7644:15)
        at new Connect (webpack:///~/react-redux/lib/components/connect.js:131:0 <- test-bundler.js:104049:36)
        at ShallowComponentWrapper._constructComponentWithoutOwner (webpack:///~/react/lib/ReactCompositeComponent.js:307:0 <- test-bundler.js:60322:27)
        at ShallowComponentWrapper.mountComponent (webpack:///~/react/lib/ReactCompositeComponent.js:192:0 <- test-bundler.js:60207:21)
        at Object.mountComponent (webpack:///~/react/lib/ReactReconciler.js:47:0 <- test-bundler.js:29520:35)
        at ReactShallowRenderer._render (webpack:///~/react/lib/ReactTestUtils.js:402:0 <- test-bundler.js:113323:21)
        at _batchedRender (webpack:///~/react/lib/ReactTestUtils.js:383:0 <- test-bundler.js:113304:12)
        at Object.batchedUpdates (webpack:///~/react/lib/ReactDefaultBatchingStrategy.js:61:0 <- test-bundler.js:61729:7)
        at Object.batchedUpdates (webpack:///~/react/lib/ReactUpdates.js:98:0 <- test-bundler.js:8372:20)
        at ReactShallowRenderer.render (webpack:///~/react/lib/ReactTestUtils.js:376:0 <- test-bundler.js:113297:16)

  selectDeleteMeDomain

```

**Comment by mxstbr** [comment]
Fixed by the amazing @lsanders in #997!
